### ISSUE TITLE
Problem after upgrading to UIKit Version 1.5.3

### ISSUE THREAD

**Issue by tpark-amity** [EkoCommunications/Amity-Social-Cloud-Q-A#13]
Question from Vodworks:

As earlier I was able to set user metadata with upstra client and it will reflect on the admin panel but now it's giving me error 800110. 
I tried with the previous user id to open the profile screen and it shows an empty screen even though the display name was not visible on EkoUserProfilePageViewController.
I am also getting null value in UpstraUIKit.client.currentUser.

**Comment by stevenwangamity** [comment]
@tanawateko please help check this one

**Comment by tanawateko** [comment]
@tpark-amity , Hi , is this the UIKIT you download from the Sample app one ? what is your API key you are using

**Comment by tpark-amity** [comment]
@tanawateko No, this is a different matter from the sample app. I will send the API key to you in private.

**Comment by tpark-amity** [comment]
> @tanawateko No, this is a different matter from the sample app. I will send the API key to you in private.

API Key sent to you in private.
