### ISSUE TITLE
[Referring to Issue #20] Back button presented on "Post to Timeline" screen and is not functional

### ISSUE THREAD

**Issue by tpark-amity** [EkoCommunications/Amity-Social-Cloud-Q-A#22]
Referring back to issue #20, the "Post to Timeline" screen has a back button instead of an "X" as shown in the sample app. The back button on that screen is also not functional which makes going back to the "NewsFeed" screen impossible at the moment.

To give you a better explanation, I'm not presenting or pushing any Upstra UIKit screen, but merely passing reference to the main screen on tap of each tab in the below screen. I also have no control over the UIKit screen either. Although I'm using a navigation controller for the main container in which I'm passing references for SDK Screens.

![image](https://user-images.githubusercontent.com/74768384/104283210-caff4080-54e2-11eb-87b7-7b952a6c7b72.png)

The "Post to Timeline" screen with a back button where it should be an "X" button to close the modal.
![103504509-38c7be80-4e8a-11eb-9230-6858554e36f9](https://user-images.githubusercontent.com/74768384/104283347-fbdf7580-54e2-11eb-879f-1d16f277a704.jpeg)

(Edit) I would like to add additional information as follows:

https://user-images.githubusercontent.com/74768384/104404482-5af9c480-558d-11eb-963e-104a57a043e1.mp4

Video 1 - Without Navigation: I have removed my navigation controller and as you can see back buttons from all Upstra screens after push are hidden.

https://user-images.githubusercontent.com/74768384/104404514-6816b380-558d-11eb-884c-97539db35268.mp4

Video 2 - Without Navigation: Still no navigation controller added to the container but you can see when tapping on a pencil it presents a controller with a navigation bar on top. and even it can push to new screens and back button there is visible. It implies that the SDK is presenting a navigation controller, not a view controller.

https://user-images.githubusercontent.com/74768384/104404561-82e92800-558d-11eb-8dbc-25878f75b070.mp4

Video 3 - With Navigation: As I have added my navigation controller to the container back buttons on all pushed screens are visible but still on the new post screen it's not working because that button presenting and pop will not work on the present. Also, the navigation bar of my controller is not overlapping any component since you can check in previous videos.

**Comment by upstrasupport** [comment]
Good evening @tpark-amity, thank you for your inquiry and sorry for the late response. 
May we ask a question? Which platform and OS version that you faced the symptoms? 
Thank you very much.

**Comment by tpark-amity** [comment]
> Good evening @tpark-amity, thank you for your inquiry and sorry for the late response.
> May we ask a question? Which platform and OS version that you faced the symptoms?
> Thank you very much.

Upstra UIKit Version: '1.5.3'
Upstra SDK Version: latest
OS Version: Catalina 10.15.5
Xcode: 11.5
CL Tools: 11.5

**Comment by siengnonta** [comment]
A navigation bar issue was fixed on version 1.7.0 and we suggest upgrading to the latest version 1.8.1, which included customization enhancement and bug fixes.

**Comment by tpark-amity** [comment]
> A navigation bar issue was fixed on version 1.7.0 and we suggest upgrading to the latest version 1.8.1, which included customization enhancement and bug fixes.

I found an issue while upgrading from 1.5.3 to 1.8.1, the details are as follow:
This happens when I upgrade to any version from 1.5.3

![WhatsApp Image 2021-01-18 at 20 13 10](https://user-images.githubusercontent.com/74768384/104993480-78c79d80-5a55-11eb-9950-667d5ac174c7.jpeg)

Please advise.

**Comment by siengnonta** [comment]
We had tried installing over `pod install` command on a couple of Xcode cl tool versions -- 11.3.1. 11.5.1, 12.2. 
As a result, the installation works fine and doesn't found the issue.
<img width="801" alt="Screen Shot 2564-01-22 at 10 59 18" src="https://user-images.githubusercontent.com/28087619/105444703-efa4a680-5ca0-11eb-8ff5-59c06209297b.png">

One thing I'm guessing is the current gem version isn't compatible with nanimo, a serialization tool, version.
Please following this link, I hope it helps.
https://github.com/CocoaPods/CocoaPods/issues/6124#issuecomment-272639357

**Comment by tpark-amity** [comment]
> We had tried installing over `pod install` command on a couple of Xcode cl tool versions -- 11.3.1. 11.5.1, 12.2.
> As a result, the installation works fine and doesn't found the issue.
> <img alt="Screen Shot 2564-01-22 at 10 59 18" width="801" src="https://user-images.githubusercontent.com/28087619/105444703-efa4a680-5ca0-11eb-8ff5-59c06209297b.png">
> 
> One thing I'm guessing is the current gem version isn't compatible with nanimo, a serialization tool, version.
> Please following this link, I hope it helps.
> [CocoaPods/CocoaPods#6124 (comment)](https://github.com/CocoaPods/CocoaPods/issues/6124#issuecomment-272639357)

Still facing the issue, have updated Ruby, Brew, and Gems.

**Comment by siengnonta** [comment]
Another solution is installing manually. Can you please try the following steps?
1. remove Upstra from your workspace (by removing `pod 'UpstraUIKit'` from podfile and run `pod install`)
2. download Upstra 1.8.2 from this [link](https://github.com/EkoCommunications/EkoMessagingSDKUIKit/releases/download/1.8.2/Distribution.zip)
3. unzip Distribution.zip and drag `UpstraUIKit.xcframework`, `EkoChat.xcframework` and `Realm.xcframework` to workspace manually
4. clean and build

**Comment by tpark-amity** [comment]
> Another solution is installing manually. Can you please try the following steps?
> 
> 1. remove Upstra from your workspace (by removing `pod 'UpstraUIKit'` from podfile and run `pod install`)
> 2. download Upstra 1.8.2 from this [link](https://github.com/EkoCommunications/EkoMessagingSDKUIKit/releases/download/1.8.2/Distribution.zip)
> 3. unzip Distribution.zip and drag `UpstraUIKit.xcframework`, `EkoChat.xcframework` and `Realm.xcframework` to workspace manually
> 4. clean and build

Navigation issue resolved after update to 1.8.2, thank you for your help!
