### ISSUE TITLE
UIKit - Cannot post picture to timeline

### ISSUE THREAD

**Issue by tpark-amity** [EkoCommunications/Amity-Social-Cloud-Q-A#24]
![image](https://user-images.githubusercontent.com/74768384/107332258-861cf880-6ae6-11eb-988f-2d9250f78e9d.png)

Problem: Cannot post a picture to timeline, loading bar stuck at 100%

Expected Behavior: User should be able to post a picture to timeline

**Comment by tpark-amity** [comment]
Simulator: iPhone 12 Pro Max
UIKit Version: 1.8.2
iOS Version: 14.4

**Comment by upstrasupport** [comment]
Hello @tpark-amity,

Thank you for raising this issue.
As we are looking into it, this case seems to be an incident or bug.
Could you please send more details regarding this issue to support.upstra@amity.co?  Our team will investigate this case and provide the update to you accordingly.
