### ISSUE TITLE
A community is missing from the admin panel

### ISSUE THREAD

**Issue by tpark-amity** [EkoCommunications/Amity-Social-Cloud-Q-A#25]
There should be two communities present in the community tab. However, one of the communities suddenly disappeared from view.

![Screen Shot 2021-02-09 at 15 41 27](https://user-images.githubusercontent.com/74768384/107337700-486f9e00-6aed-11eb-97a4-fced0465c55f.png)

By direct query with an API, it still shows two communities with isDeleted as false.

Please advise on how to get that one community back into view on the admin panel.

Admin Panel Version: 4.3.11

**Comment by stevenwangamity** [comment]
Hi @tpark-amity , thanks for reporting. This is a known issue and we are fixing it. As a workaround, you can filter "flagged" community to see the "disappeared" communities

**Comment by tpark-amity** [comment]
> Hi @tpark-amity , thanks for reporting. This is a known issue and we are fixing it. As a workaround, you can filter "flagged" community to see the "disappeared" communities

Just noticed that as well. One more issue is some posts are not appearing in the community. The flagged comment is on that post in which I have no way to delete the comment or simply check it out.

**Comment by stevenwangamity** [comment]
@tpark-amity For posts, it has the same issue, and the workaround is to use the "flagged" filter

**Comment by tpark-amity** [comment]
> @tpark-amity For posts, it has the same issue, and the workaround is to use the "flagged" filter

I see. Got it. Another side note is that even if I deleted the post that contains the flagged comment, the filter still applies the same behavior as if the comment is still there.

**Comment by stevenwangamity** [comment]
@tpark-amity yes, that's expected behavior

**Comment by tpark-amity** [comment]
> @tpark-amity yes, that's expected behavior

Got it, thanks. Hope this issue can be resolved soon.

**Comment by stevenwangamity** [comment]
@tpark-amity please note that the fix was published yesterday and you should be able to see the data now
