### ISSUE TITLE
How does the system store data?

### ISSUE THREAD

**Issue by tpark-amity** [EkoCommunications/Amity-Social-Cloud-Q-A#27]
I'm wondering how do you store sensitive data at the moment? Do you store it in plain text? If not, what do you use to encrypt sensitive data?

**Comment by tpark-amity** [comment]
Also, what kinds of cryptography and security protocols that you use to safeguard sensitive data during transmission over open, public networks, and intranet?

**Comment by stevenwangamity** [comment]
@tpark-amity we don't store any sensitive data for end users from any client, all we store is only the user id which is used for feature purpose and also passed by client.

**Comment by tpark-amity** [comment]
> @tpark-amity we don't store any sensitive data for end users from any client, all we store is only the user id which is used for feature purpose and also passed by client.

Do you plan to store any sensitive data in the future? If so, what kinds of measure will you take for this?

**Comment by stevenwangamity** [comment]
@tpark-amity we don't have any plan to store sensitive data in the near future

**Comment by tpark-amity** [comment]
> @tpark-amity we don't have any plan to store sensitive data in the near future

Thank you so much.
