### ISSUE TITLE
Does Amity limits access to system components and sensitive data to only people whose job requires it?

### ISSUE THREAD

**Issue by tpark-amity** [EkoCommunications/Amity-Social-Cloud-Q-A#28]

**Comment by stevenwangamity** [comment]
@tpark-amity we don't store any sensitive data for end users from any client, and we only provide one admin panel credential to the client contact point and internal product managers & senior engineers and never spread to other members

**Comment by tpark-amity** [comment]
> @tpark-amity we don't store any sensitive data for end users from any client, and we only provide one admin panel credential to the client contact point and internal product managers & senior engineers and never spread to other members

Noted, thank you.
