### ISSUE TITLE
Is there any restriction of access in which an individual have to perform job responsibilities at Amity?

### ISSUE THREAD

**Issue by tpark-amity** [EkoCommunications/Amity-Social-Cloud-Q-A#29]
To elaborate, does an individual who has such access be given the least privilege necessary to perform his/her job?

**Comment by stevenwangamity** [comment]
@tpark-amity could you please elaborate what you mean by "such access", thanks

**Comment by tpark-amity** [comment]
> @tpark-amity could you please elaborate what you mean by "such access", thanks

By such access, I mean access to any data or platform of ASC.

**Comment by stevenwangamity** [comment]
@tpark-amity Amity staffs are granted the access to admin panel in order to help answer questions / resolve issues, but some actions require super admin users to perform

**Comment by tpark-amity** [comment]
> @tpark-amity Amity staffs are granted the access to admin panel in order to help answer questions / resolve issues, but some actions require super admin users to perform

Understood, thank you.
