### ISSUE TITLE
Cannot find setEkoConfig method in EkoClient after upgrading UIKit from 1.8.2 to 1.9.2

### ISSUE THREAD

**Issue by tpark-amity** [EkoCommunications/Amity-Social-Cloud-Q-A#42]
The current implementation uses "EkoClient.setEkoConfig" method in configuring the Eko SDK Environment as following value: ["sdk_environment":"https://api.ekomedia.technology/"]

However, the current UIKit version (1.9.2) seems to not have this method anymore. I suspect that the name changes to setDomainKey instead. Does this have the same functionality?

I tried passing in EkoClient.setDomainKey("https://api.ekomedia.technology") and it still doesn't work.

Please advise as this is currently a breaking change. Thank you.

**Comment by siengnonta** [comment]
UIkit 1.9.2 comes with EkoChat 4.6.0, which environment setup has been deprecated and customers/developers are not allow to access `setEkoConfig` function.
As a result, env for customers will be the same and unable to change.
