### ISSUE TITLE
[Web] Live Streaming Overlay

### ISSUE THREAD

**Issue by tpark-amity** [EkoCommunications/Amity-Social-Cloud-Q-A#43]
I would like to have an overlay over a live streaming session in which the overlay should be able to:
- Show an image
- Show text
- Able to link to a new page (new tab) after a click

There are two scenarios I would like to question: With UIKit (web) and without UIKit

With UIKit:
If this is not readily available, can this be customizable if I have the source code for the Web UIKit by me?

Without UIKit:
I would assume that I can use ASC as the backend for live streaming and make my own player and overlay, would that be the right approach in this case?

The last question would be: What would be the fastest way to implement this functionality? With or without UIKit?

Thank you.

**Comment by touchaponk** [comment]
There's currently no video player component in the Web SDK or UIKit but clients can easily use third party video player like video js or even a built-in HTML video player.  Given that live video stream will be encapsulated into a video player in the website, building overlay should be possible by overlaying desired images, texts and other html component on top of the player itself.

**Comment by tpark-amity** [comment]
> There's currently no video player component in the Web SDK or UIKit but clients can easily use third party video player like video js or even a built-in HTML video player. Given that live video stream will be encapsulated into a video player in the website, building overlay should be possible by overlaying desired images, texts and other html component on top of the player itself.

Alright, thank you.
